using Bridge.Core.App.Manager;
using System;
using System.Diagnostics;
using System.IO;
using UnityEngine;

namespace Bridge.Core.UnityEditor.App.Manager
{
    public static class BuildCompilerScript
    {
        public static void BuildCompiler(BuildSettingsData buildSettings)
        {
            try
            {
                #region Header Data

                string compilerFileName = "Compiler.bat";
                string buildCompilerFileName = "BuildCompiler.bat";
                string CleanerFileName = "CleanBuild.bat";

                #endregion

                #region Compiler

                var compilerData = new FileInfo(compilerFileName);
                string compilerDir = compilerData.DirectoryName;
                string compileScriptsDir = compilerDir + GetBuildScriptFolderName();
                string compilerFilePath = compileScriptsDir + "/" + compilerData.Name;

                #endregion

                #region Build Compiler

                var buildCompilerData = new FileInfo(buildCompilerFileName);
                string buildCompilerDir = buildCompilerData.DirectoryName;
                string buildScriptsDir = buildCompilerDir + GetBuildScriptFolderName();
                string buildScriptsFilePath = buildScriptsDir + "/" + buildCompilerData.Name;

                #endregion

                #region Build Cleaner

                var cleanerData = new FileInfo(CleanerFileName);
                string cleanerDirectoryName = cleanerData.DirectoryName;
                string cleanerDirectoryFolder = cleanerDirectoryName + GetBuildScriptFolderName();
                string cleanerFilePath = cleanerDirectoryFolder + "/" + cleanerData.Name;

                #endregion

                UnityEngine.Debug.Log($"Creating Compiler - Directory : {buildScriptsDir} - File Path : {buildScriptsFilePath}");

                if (!Directory.Exists(buildScriptsDir))
                {
                    Directory.CreateDirectory(buildScriptsDir);
                    UnityEngine.Debug.Log($"--> Creating Build Compiler Directory : <color=cyan>{buildScriptsDir}</color>");
                }

                string targetDest = Path.GetTempPath();
                string targetDestDir = Path.Combine(targetDest, buildSettings.appInfo.appName.Replace(" ", string.Empty));

                UnityEngine.Debug.Log($"--> Target Directory : <color=cyan>{targetDestDir}</color>");

                if (!Directory.Exists(targetDestDir))
                {
                    UnityEngine.Debug.Log($"--> Creating Temp Build Project Directory @ : <color=cyan>{targetDestDir}</color>");
                    Directory.CreateDirectory(targetDestDir);
                }

                //string excludedFolders = "/E /xd Library Temp Build Builds Obj Logs UserSettings MemoryCaptures";
                string excludedFolders = "/E /xd ";

                string projectBuildRemovePath = (Directory.Exists(targetDestDir)) ? "@RD /S /Q " + targetDestDir : string.Empty;

                if (!string.IsNullOrEmpty(projectBuildRemovePath))
                {
                    UnityEngine.Debug.Log($"--> Purging All Project Data @ : <color=orange>{targetDestDir}</color>");
                }

                string cleanBuildPathCommand = $"rmdir \"{targetDestDir.Replace("/", "\\")}\" /q /s";

                string builds = "*.apk *.exe *.aab *.unitypackage";
                //string autoGenerated = "*.csproj *.unityproj *.sln *.suo *.tmp *.user *.userprefs *.pidb *.booproj *.svd *.pdb *.mdb *.opendb *.VC.db";
                string autoGenerated = "";
                string excludeFiles = $"/xf {autoGenerated} {builds}";

                //string projectCopyCommand = $"robocopy {buildCompilerDir} {targetDestDir} {excludedFolders} {excludeFiles}";
                string projectCopyCommand = $"robocopy {buildCompilerDir} {targetDestDir} {excludedFolders} {excludeFiles}";

                // Build Command
                string rootPath = "C:/Program Files/";
                string unityVersion = Application.unityVersion;
                string path = "/Editor/Unity.exe";
                string pathCombined = "\"" + rootPath + unityVersion + path + "\"";
                string compilerDirectory = $"\"{targetDestDir.Replace("\\", "/")}{GetBuildScriptFolderName()}\"";
                string targetDirectory = $"\"{targetDestDir.Replace("\\", "/")}\"";
                string changeToBuildDirectoryCommand = "chdir /d " + compilerDirectory;
                string changeToProjectDirectoryCommand = "chdir /d " + buildCompilerDir;
                string buildMethodName = "AppBuildConfig.BuildApp";
                string buildCommand = pathCombined + $" -quit -batchMode -projectPath .. -executeMethod {buildMethodName}";
                
                // Batch File Path
                string compilerBatchFile = "./" + compilerFileName;
                string cleanerBatchFile = "./" + CleanerFileName;

                UnityEngine.Debug.Log($"-->Change To Temp Compiler Directory : {changeToBuildDirectoryCommand}");

                string projectDir = "chdir /d " + targetDestDir;

                string openBuildFolderPath = $"Start \"\" \"{buildSettings.configurations.targetBuildDirectory}\"";

                string buildDir = $"{targetDestDir}\\Builds";
                string moveBuildCommand = $"move {buildDir}\\*.* {buildSettings.configurations.targetBuildDirectory.Replace("/","\\")}";

                string purgeCacheCommand = $"rmdir {targetDestDir}";

                UnityEngine.Debug.Log($"-->Copy Build To : {moveBuildCommand}");

                UnityEngine.Debug.Log($"-->Change To Build Compiler Directory : {projectDir}");

                #region Editor Log

                string logDir = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
                string editorLogDir = $"{logDir}\\Unity\\Editor\\Editor.log";
                string logEditorCommand = $"Type {editorLogDir}";
                UnityEngine.Debug.Log($"-->Data Directory : {editorLogDir}");

                #endregion

                Compiler compiler = new Compiler
                {
                    echoOff = "@echo off",
                    echoInitializeBuild = "echo Initializing Project Build...",
                    editorLogBuildStarted = logEditorCommand,
                    startBuildCommand = buildCommand,
                    moveBuildCommand = moveBuildCommand,
                    purgeCacheCommand = purgeCacheCommand,
                    openBuildFolderPath = openBuildFolderPath,
                    changeToProjectDirectory = changeToProjectDirectoryCommand,
                    editorLogBuildEnded = logEditorCommand,
                    cleanBuildCommand = cleanerBatchFile,
                    pause = "@pause"
                };

                BuildCompiler buildCompiler = new BuildCompiler
                {
                    echoOff = "@echo off",
                    echoPrepareBuild = "echo Preparing Build...",
                    removeDirectoryCommand = projectBuildRemovePath,
                    echoCopy = "echo Copying Build Files...",
                    copyCommand = projectCopyCommand,
                    changeToBuildDirectory = changeToBuildDirectoryCommand,
                    echoCompile = "echo Compiling Build Scripts...",
                    compilerBuildCommand = compilerBatchFile,
                    pause = "@pause"
                };

                BuildCleaner buildCleaner = new BuildCleaner
                {
                    echoOff = "@echo off",
                    echoCleaningBuild = "echo Cleaning Build Project...",
                    cleanBuildPathCommand = cleanBuildPathCommand,
                    echoEndBuild = "echo Build Completed...",
                    pause = "@pause"
                };

                // Batch Files
                CreateBatchFile(compilerFilePath, compiler);
                CreateBatchFile(buildScriptsFilePath, buildCompiler);
                CreateBatchFile(cleanerFilePath, buildCleaner);

                if (File.Exists(buildScriptsFilePath))
                {
                    UnityEngine.Debug.Log($"--> <color=orange>Build Started....</color>");
                    StartBatchBuildCommand(buildScriptsFilePath);
                }
            }
            catch (Exception exception)
            {
                throw exception;
            }
        }

        private static void CreateBatchFile<T>(string path, T fileData)
        {
            File.WriteAllText(path, fileData.ToString());
        }

        private static string GetBuildScriptFolderName()
        {
            return "\\BuildScripts";
        }

        public static void OpenBuildFolder()
        {
            string buildFolderPath = AppBuildManagerEditor.GetBuildSettings(AppBuildManagerEditor.GetDefaultStorageInfo()).configurations.targetBuildDirectory;

            if (Directory.Exists(buildFolderPath))
            {
                Process.Start("explorer.exe", buildFolderPath.Replace("/", "\\"));
            }
        }

        private static void StartBatchBuildCommand(string buildCommand)
        {
            Process.Start(buildCommand);
        }
    }
}
